# Runs one benchmark case in this process. run_bench.R and burnin.R run each case in a fresh,
# memory-capped process with this script, so that cases don't share memory peaks.
#
# Usage: Rscript bench/case.R <pandemic|endemic|burnin> <human_population> <rep> <output csv>
source("bench/common.R")
load_helios()

args <- commandArgs(trailingOnly = TRUE)
scenario <- args[1]
human_population <- as.numeric(args[2])
rep <- as.integer(args[3])
output <- args[4]

if (scenario == "burnin") {
  parameters <- bench_parameters("endemic", human_population, simulation_time = BURNIN_DAYS)
  population <- measure(generate_population_data(parameters))
  run <- measure(run_simulation(parameters, population$value))
  path <- burnin_path(human_population)
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  saveRDS(list(
    population = population$value,
    state = run$value$state,
    # Kept to check the burn-in reached equilibrium
    result = run$value$result,
    commit = git_commit()
  ), path)
  message(sprintf(
    "burn-in N=%d: %.0f s, peak %.0f MB, saved to %s",
    human_population, population$seconds + run$seconds, max(population$peak_mb, run$peak_mb), path
  ))
  quit(save = "no")
}

if (scenario == "pandemic") {
  parameters <- bench_parameters("pandemic", human_population, simulation_time = PANDEMIC_DAYS)
  population <- measure(generate_population_data(parameters))
  run <- measure(run_simulation(parameters, population$value))
  simulated_days <- PANDEMIC_DAYS
} else if (scenario == "endemic") {
  path <- burnin_path(human_population)
  if (!file.exists(path)) stop("no burn-in for N=", human_population, ": run bench/burnin.R first")
  burnin <- readRDS(path)
  parameters <- bench_parameters("endemic", human_population, simulation_time = ENDEMIC_TIMED_DAYS)
  # The population is generated by the burn-in, so isn't timed here
  population <- list(seconds = NA, peak_mb = NA)
  run <- measure(run_simulation(parameters, burnin$population, state = burnin$state))
  simulated_days <- ENDEMIC_TIMED_DAYS
} else {
  stop("unknown scenario: ", scenario)
}

append_csv(data.frame(
  date = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
  commit = git_commit(),
  scenario = scenario,
  human_population = human_population,
  rep = rep,
  status = "ok",
  simulated_days = simulated_days,
  population_seconds = population$seconds,
  population_peak_mb = population$peak_mb,
  run_seconds = run$seconds,
  run_peak_mb = run$peak_mb,
  seconds_per_day = run$seconds / simulated_days
), output)
