#' Define and create all model processes
#'

#' @param variables_list A list of model variables as generated by [create_variables()]
#' @param events_list A list of the model events as generated by [create_events()]
#' @param parameters_list A list of model parameters as generated by [get_parameters()]
#' @param population_data A list representing the population, as generated by [generate_population_data()]
#' @param intervention_data A list of intervention coverage and efficacy, as generated by
#'   [generate_intervention_data()]
#' @param renderer An individual-package render object
#'
#' @family processes
#' @export
create_processes <- function(
  variables_list,
  events_list,
  parameters_list,
  population_data,
  intervention_data,
  renderer
) {
  # Open a list of processes to store the model processes in:
  processes_list <- list(
    # ===============================
    # Disease State Progression
    # ===============================
    SE_process = create_SE_process(
      variables_list = variables_list,
      events_list = events_list,
      parameters_list = parameters_list,
      population_data = population_data,
      intervention_data = intervention_data,
      renderer = renderer
    ),

    EI_process = create_EI_process(
      variables_list = variables_list,
      events_list = events_list,
      parameters_list = parameters_list,
      renderer= renderer
    ),

    I_mild_R_process = create_I_mild_R_process(
      variables_list = variables_list,
      events_list = events_list,
      parameters_list = parameters_list,
      renderer= renderer
    ),

    I_hosp_exit_process = create_I_hosp_exit_process(
      variables_list = variables_list,
      events_list = events_list,
      parameters_list = parameters_list,
      renderer= renderer
    )
  )

  # ===============================
  # ENDEMIC DISEASE MODE
  # ===============================
  if (parameters_list$endemic_or_epidemic == "endemic") {
    processes_list <- c(
      processes_list,
      list(
        RS_process = create_RS_process(
          variables_list = variables_list,
          events_list = events_list,
          parameters_list = parameters_list
        )
      ),
      list(
        external_source_process = create_external_source_process(
          variables_list = variables_list,
          events_list = events_list,
          parameters_list = parameters_list,
          renderer = renderer
        )
      )
    )
  }

  # ===============================
  # Rendering processes
  # ===============================
  # health_render_process
  processes_list <- c(
    processes_list,
    renderer = individual::categorical_count_renderer_process(
      renderer,
      variables_list$disease_state,
      c('S', 'E', 'I_mild', 'I_hosp', 'R', 'D')
    )
  )

  # Return the model processes:
  return(processes_list)
}

#' Create process governing susceptible to exposed disease state transition
#'
#' In a household, school or workplace, the force of infection on each member is
#' `riskiness * beta * I / size` for `I` infectious members out of `size`.
#'
#' Schools and workplaces can also have non-resident members, who aren't
#' simulated (see the `non_residents` parameter and
#' [generate_population_data()]). Nothing is known about them, so they are
#' assumed to be like the simulated population: at each timestep, the number of
#' infectious non-residents in each setting is drawn from a binomial
#' distribution, with the setting's number of non-residents and the proportion of
#' the simulated population that is infectious. They add to both `I` and `size`.
#' Non-residents are never infected themselves, so they bring in infection in
#' proportion to the simulated epidemic and none when it is over.
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_SE_process <- function(
  variables_list,
  events_list,
  parameters_list,
  population_data,
  intervention_data,
  renderer
) {
  N <- parameters_list$human_population

  # Each individual's household, school and workplace (0 = none), and the number of individuals in
  # each location. These don't change during the simulation.
  household <- population_data$initial_household_settings
  school <- population_data$initial_school_settings
  workplace <- population_data$initial_workplace_settings
  household_size <- population_data$setting_sizes$household
  school_size <- population_data$setting_sizes$school
  workplace_size <- population_data$setting_sizes$workplace
  lives_alone <- household_size[household] == 1

  # Non-resident members of each school and workplace. Populations generated without them have none.
  school_non_residents <- non_resident_members(population_data, "school", length(school_size))
  workplace_non_residents <- non_resident_members(population_data, "workplace", length(workplace_size))

  # The leisure location each individual could visit on each day of the week (0 = none), with one
  # column per individual
  stopifnot(all(lengths(population_data$initial_leisure_settings) == 7))
  leisure_week <- matrix(
    as.integer(unlist(population_data$initial_leisure_settings, use.names = FALSE)),
    nrow = 7
  )
  num_leisure <- length(population_data$leisure_specific_riskiness)

  # Each location's riskiness at timestep t, reduced by the setting's intervention once it's in place
  riskiness_at <- function(setting, t) {
    riskiness <- population_data[[paste0(setting, "_specific_riskiness")]]
    if (
      parameters_list[[paste0("intervention_", setting, "_active")]] &&
        t > parameters_list[[paste0("intervention_", setting, "_timestep")]]
    ) {
      riskiness <- riskiness * (1 - intervention_data$efficacy[[setting]])
    }
    riskiness
  }

  ## Process Function
  function(t) {
    ## Indices of all infectious individuals
    I <- variables_list$disease_state$get_index_of("I_mild")$to_vector()

    #=== time-varying modification of betas ===#
    #=================================#
    # When time-varying transmission is on, each setting-specific beta is a vector with one
    # value per simulated day; the timestep t is converted to a day via
    # timestep_to_day() (1/dt timesteps per day) and that day's value is used.
    # When time-varying transmission is off, each setting-specific beta is a single constant
    # value used for every timestep.
    if (parameters_list$time_varying_transmission_on) {
      day <- timestep_to_day(t, parameters_list$dt)
      beta_household_t <- parameters_list$beta_household[day]
      beta_workplace_t <- parameters_list$beta_workplace[day]
      beta_school_t <- parameters_list$beta_school[day]
      beta_leisure_t <- parameters_list$beta_leisure[day]
      beta_community_t <- parameters_list$beta_community[day]
    } else {
      beta_household_t <- parameters_list$beta_household
      beta_workplace_t <- parameters_list$beta_workplace
      beta_school_t <- parameters_list$beta_school
      beta_leisure_t <- parameters_list$beta_leisure
      beta_community_t <- parameters_list$beta_community
    }

    #=== Household FOI ===#
    #=====================#
    # Individuals living alone can't be infected at home
    household_FOI <- location_FOI(
      household, I, riskiness_at("household", t), beta_household_t, household_size
    )
    household_FOI[lives_alone] <- 0

    #=== Workplace FOI ===#
    #=====================#
    prevalence <- length(I) / N
    workplace_FOI <- location_FOI(
      workplace, I, riskiness_at("workplace", t), beta_workplace_t, workplace_size,
      workplace_non_residents, prevalence
    )

    #=== School FOI ===#
    #==================#
    school_FOI <- location_FOI(
      school, I, riskiness_at("school", t), beta_school_t, school_size,
      school_non_residents, prevalence
    )

    #=== Leisure FOI ===#
    #=====================#
    if ((t * parameters_list$dt) == floor((t * parameters_list$dt))) {
      # At the start of each day, sample which of the week's leisure locations each individual visits
      # that day (0 = they stay home). Uses dqrng for speed; it is seeded alongside base R's RNG by
      # seed_rng()
      visit_day <- dqrng::dqsample.int(n = 7, size = N, replace = TRUE)
      leisure_visit <- leisure_week[cbind(visit_day, seq_len(N))]
      variables_list$specific_leisure$queue_update(leisure_visit)
    } else {
      leisure_visit <- variables_list$specific_leisure$get_values()
    }

    # Leisure FOI is shared among the individuals actually visiting each location that day
    leisure_FOI <- location_FOI(
      leisure_visit, I, riskiness_at("leisure", t), beta_leisure_t, tabulate(leisure_visit, num_leisure)
    )

    #=== Community FOI ===#
    #=====================#
    ### Calculate Community FOI (real-valued for all individuals)
    #### NOTE: Double check whether the "/N" is correct here - not sure currently
    community_FOI <- beta_community_t * length(I) / N

    #=== Total FOI ===#
    #=================#

    # Sum the household, workplace, school leisure, and community FOIs to get the total FOI for each
    # individual:
    total_FOI <- household_FOI +
      workplace_FOI +
      school_FOI +
      leisure_FOI +
      community_FOI

    # Render the setting-specific FOIs is diagnostic rendering turned on:
    if (parameters_list$render_diagnostics) {
      renderer$render('FOI_household', max(household_FOI), t)
      renderer$render('FOI_workplace', max(workplace_FOI), t)
      renderer$render('FOI_school', max(school_FOI), t)
      renderer$render('FOI_leisure', max(leisure_FOI), t)
      renderer$render('FOI_community', max(community_FOI), t)
      renderer$render('FOI_total', max(total_FOI), t)
    }

    # Calculate the probability of getting infected in the current interval for each individual:
    p_inf <- 1 - exp(-total_FOI * parameters_list$dt)

    # Get the indices of all susceptible individuals in the current timestep:
    S <- variables_list$disease_state$get_index_of("S")

    # Get the infection probability for each currently susceptible individual:
    p_inf_currently_S <- p_inf[S$to_vector()]

    # Sample susceptible individuals using their infection probability to determine who gets infected:
    S$sample(rate = p_inf_currently_S)

    # Render the number of people going from susceptible to infected:
    renderer$render('E_new', S$size(), t)

    # Queue an update to the infectious state of the newly infected susceptible individuals to Exposed:
    variables_list$disease_state$queue_update(value = "E", index = S)
  }
}


# The force of infection on each individual from the locations of one setting type
#
# `location` is each individual's location (0 = none) and `infectious` the indices of infectious
# individuals. `riskiness` and `size` are each location's riskiness and number of individuals.
# `non_residents`, if given, is each location's number of unsimulated non-resident members, NULL
# if none has any, and each is infectious with probability `prevalence`.
location_FOI <- function(location, infectious, riskiness, beta, size, non_residents = NULL, prevalence = 0) {
  num_infectious <- tabulate(location[infectious], length(size))
  if (!is.null(non_residents)) {
    size <- size + non_residents
    # One vectorised draw for every location. With no one infectious, none are drawn.
    if (prevalence > 0) {
      num_infectious <- num_infectious + stats::rbinom(length(non_residents), non_residents, prevalence)
    }
  }
  # Locations nobody attends have a FOI of NaN (0 / 0), but it's never assigned to anyone
  FOI <- riskiness * beta * num_infectious / size
  c(0, FOI)[location + 1]
}

# Each location's number of non-resident members in `setting`, from population_data$non_residents,
# or NULL if none has any (including populations generated before non-residents were added)
non_resident_members <- function(population_data, setting, num_locations) {
  counts <- population_data$non_residents[[setting]]
  if (is.null(counts) || !any(counts > 0)) {
    return(NULL)
  }
  stopifnot(length(counts) == num_locations)
  counts
}

#' Create process governing exposed to infectious disease state transition
#'
#' Performs an age-dependent binomial split of newly transitioning exposed
#' individuals between I_mild and I_hosp. Counts `H_new` at entry to I_hosp.
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_EI_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  function(t) {
    # Get exposed individuals not yet scheduled into either EI event
    E <- variables_list$disease_state$get_index_of("E")
    already_scheduled <- events_list$EI_mild_event$get_scheduled()
    already_scheduled$or(events_list$EIhosp_event$get_scheduled())
    E$and(already_scheduled$not(inplace = TRUE))

    if (E$size() == 0) return()
    E_idx <- E$to_vector()

    # Build per-person hospitalization probability based on age class
    p_hosp <- rep(NA_real_, length(E_idx))
    child_idx <- variables_list$age_class$get_index_of("child")$to_vector()
    adult_idx <- variables_list$age_class$get_index_of("adult")$to_vector()
    elderly_idx <- variables_list$age_class$get_index_of("elderly")$to_vector()
    p_hosp[E_idx %in% child_idx] <- parameters_list$prob_hosp_child
    p_hosp[E_idx %in% adult_idx] <- parameters_list$prob_hosp_adult
    p_hosp[E_idx %in% elderly_idx] <- parameters_list$prob_hosp_elderly

    # Guard: every exposed individual must have been matched to one of the
    # three age classes. NA in p_hosp would propagate to NA in hosp_draw and
    # silently drop the individual from both the mild and hosp branches.
    if (anyNA(p_hosp)) {
      stop(sprintf(
        "create_EI_process: p_hosp has %d NA entries - some exposed individuals do not match any age class",
        sum(is.na(p_hosp))
      ))
    }

    # Binomial split
    hosp_draw <- rbinom(length(E_idx), size = 1, prob = p_hosp)

    # Gamma-distributed delay until E -> I transition
    I_times <- round(
      (rgamma(
        n = length(E_idx),
        shape = 2,
        rate = 2 / parameters_list$duration_exposed
      ) + 1) / parameters_list$dt
    )

    mild_mask <- hosp_draw == 0
    hosp_mask <- hosp_draw == 1

    if (any(mild_mask)) {
      events_list$EI_mild_event$schedule(
        target = E_idx[mild_mask],
        delay = I_times[mild_mask]
      )
    }
    if (any(hosp_mask)) {
      events_list$EIhosp_event$schedule(
        target = E_idx[hosp_mask],
        delay = I_times[hosp_mask]
      )
    }

    # Count new hospitalizations at the moment severity is decided
    renderer$render("H_new", sum(hosp_mask), t)
  }
}

#' Create process governing I_mild -> R disease state transition
#'
#' All mild cases recover; no branching.
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_I_mild_R_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  function(t) {
    I_mild <- variables_list$disease_state$get_index_of("I_mild")
    already_scheduled <- events_list$I_mild_R_event$get_scheduled()
    I_mild$and(already_scheduled$not(inplace = TRUE))

    if (I_mild$size() == 0) return()

    R_times <- round(
      (rgamma(
        n = I_mild$size(),
        shape = 2,
        rate = 2 / parameters_list$duration_infectious
      ) + 1) / parameters_list$dt
    )

    events_list$I_mild_R_event$schedule(target = I_mild, delay = R_times)
  }
}

#' Create process governing I_hosp -> R or D disease state transition
#'
#' Performs an age-dependent binomial split between recovery and death.
#' Counts `D_new` at the moment the death decision is made.
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_I_hosp_exit_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  # Report 0 deaths on timesteps where nobody is hospitalised
  renderer$set_default("D_new", 0)

  function(t) {
    # Get I_hosp individuals not yet scheduled into either exit event
    I_hosp <- variables_list$disease_state$get_index_of("I_hosp")
    already_scheduled <- events_list$I_hosp_R_event$get_scheduled()
    already_scheduled$or(events_list$I_hosp_D_event$get_scheduled())
    I_hosp$and(already_scheduled$not(inplace = TRUE))

    if (I_hosp$size() == 0) return()
    I_hosp_idx <- I_hosp$to_vector()

    # Build per-person death probability based on age class
    p_death <- rep(NA_real_, length(I_hosp_idx))
    child_idx <- variables_list$age_class$get_index_of("child")$to_vector()
    adult_idx <- variables_list$age_class$get_index_of("adult")$to_vector()
    elderly_idx <- variables_list$age_class$get_index_of("elderly")$to_vector()
    p_death[I_hosp_idx %in% child_idx] <- parameters_list$prob_death_hosp_child
    p_death[I_hosp_idx %in% adult_idx] <- parameters_list$prob_death_hosp_adult
    p_death[I_hosp_idx %in% elderly_idx] <- parameters_list$prob_death_hosp_elderly

    # Guard: every hospitalized individual must have been matched to one of
    # the three age classes. NA in p_death would propagate to NA in death_draw
    # and silently drop the individual from both the recover and die branches.
    if (anyNA(p_death)) {
      stop(sprintf(
        "create_I_hosp_exit_process: p_death has %d NA entries - some hospitalized individuals do not match any age class",
        sum(is.na(p_death))
      ))
    }

    # Binomial split
    death_draw <- rbinom(length(I_hosp_idx), size = 1, prob = p_death)

    # Gamma-distributed delay (reusing duration_infectious)
    exit_times <- round(
      (rgamma(
        n = length(I_hosp_idx),
        shape = 2,
        rate = 2 / parameters_list$duration_hospitalized
      ) + 1) / parameters_list$dt
    )

    recover_mask <- death_draw == 0
    death_mask <- death_draw == 1

    if (any(recover_mask)) {
      events_list$I_hosp_R_event$schedule(
        target = I_hosp_idx[recover_mask],
        delay = exit_times[recover_mask]
      )
    }
    if (any(death_mask)) {
      events_list$I_hosp_D_event$schedule(
        target = I_hosp_idx[death_mask],
        delay = exit_times[death_mask]
      )
    }

    renderer$render("D_new", sum(death_mask), t)
  }
}

#' Create process governing recovered (and immune) back to susceptible disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_RS_process <- function(variables_list, events_list, parameters_list) {
  function(t) {
    # Get the indices of currently recovered and immune individuals:
    R <- variables_list$disease_state$get_index_of("R")

    # Get the indices of individuals with I to R transitions already scheduled:
    RS_already_scheduled <- events_list$RS_event$get_scheduled()

    # Get the indices of infectious individuals without R to S transitions already scheduled:
    R$and(RS_already_scheduled$not(inplace = TRUE))

    # Calculate recovery times for infectious individuals without transitions scheduled:
    S_times <- round(
      rgamma(
        n = R$size(),
        shape = 1,
        rate = 1 / parameters_list$duration_immune
      ) /
        parameters_list$dt
    )

    # Schedule the recovery events for infectious individuals without transitions scheduled:
    events_list$RS_event$schedule(target = R, delay = S_times)
  }
}

#' Create process governing exposed to infectious disease state transition
#'
#' @inheritParams create_processes
#'
#' @family processes
#' @export
create_external_source_process <- function(
  variables_list,
  events_list,
  parameters_list,
  renderer
) {
  function(t) {
    # Get the indices of all susceptible individuals:
    S_endemic <- variables_list$disease_state$get_index_of("S")

    # Calculate the probability of getting infected in the current interval for each individual:
    p_inf_ext <- 1 -
      exp(-parameters_list$prob_inf_external * parameters_list$dt)

    # Sample susceptible individuals using their infection probability to determine who gets infected:
    S_endemic$sample(rate = p_inf_ext)

    # Queue an update to the infectious state of the newly infected susceptible individuals to Exposed:
    variables_list$disease_state$queue_update(value = "E", index = S_endemic)

    # Render the number of individuals infected through the external mechanism
    renderer$render('n_external_infections', S_endemic$size(), t)
  }
}
