DISEASE_STATES <- c("S", "E", "I_mild", "I_hosp", "R", "D")
AGE_CLASSES <- c("child", "adult", "elderly")

#' Generate a list of the model variables
#'
#' @param parameters_list A list of model parameters as generated by `get_parameters`
#' @param population_data The population data, as generated by [generate_population_data()]
#'
#' @family variables
#' @export
create_variables <- function(parameters_list, population_data) {
  disease_state_variable <- individual::CategoricalVariable$new(
    categories = DISEASE_STATES,
    initial_values = population_data$initial_disease_states
  )

  age_class_variable <- individual::CategoricalVariable$new(
    categories = AGE_CLASSES,
    initial_values = population_data$age_classes
  )

  # Everyone belongs to a household, so household ids start at 1. For schools,
  # workplaces and leisure, 0 means the individual doesn't attend any location.
  # Ids are formatted with "%d" so that large ids aren't written in scientific
  # notation (eg. `as.character(1e5)` is "1e+05").
  household_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", seq_along(population_data$setting_sizes$household)),
    initial_values = sprintf("%d", population_data$initial_household_settings)
  )

  school_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$school)),
    initial_values = sprintf("%d", population_data$initial_school_settings)
  )

  workplace_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$workplace)),
    initial_values = sprintf("%d", population_data$initial_workplace_settings)
  )

  leisure_variable <- individual::RaggedInteger$new(
    initial_values = population_data$initial_leisure_settings
  )

  ## Creating initial CategoricalVariable tracking leisure location an individiual goes to on a given day, which we will dynamically update
  specific_leisure_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$leisure)),
    initial_values = rep("0", parameters_list$human_population)
  )

  return(list(
    disease_state = disease_state_variable,
    age_class = age_class_variable,
    household = household_variable,
    school = school_variable,
    workplace = workplace_variable,
    leisure = leisure_variable,
    specific_leisure = specific_leisure_variable
  ))
}

#' Generate a population for the given parameters
#'
#' This will sample individuals' initial state and assign them to households and
#' other locations. It also draws the baseline ACH and riskiness of each
#' location. Interventions are not part of the population: see
#' [generate_intervention_data()].
#'
#' @param parameters_list A list of model parameters as generated by `get_parameters`
#' @family variables
#' @export
generate_population_data <- function(parameters_list) {
  # Disease state variable
  initial_disease_states <- generate_initial_disease_states(parameters_list = parameters_list)

  # Bootstrap sampling of households, and the ages of their members, from the RTI synthetic
  # population for San Francisco
  household_age_list <- generate_initial_households(parameters_list = parameters_list)
  initial_age_classes <- household_age_list$age_class_vector
  initial_households <- household_age_list$individual_households

  initial_school_settings <- generate_initial_schools(
    parameters_list = parameters_list,
    initial_age_classes = initial_age_classes
  )

  initial_workplace_settings <- generate_initial_workplaces(
    parameters_list = parameters_list,
    initial_age_classes = initial_age_classes,
    initial_school_settings = initial_school_settings
  )

  # Generating the number and sizes of each leisure setting
  leisure_setting_sizes <- sample_negbinom(
    N = parameters_list$human_population,
    prop_max = parameters_list$leisure_prop_max,
    mu = parameters_list$leisure_mean_size,
    size = parameters_list$leisure_overdispersion_size
  )

  # Initialise and populate the leisure setting variable that stores all the leisure locations an individual COULD go to
  initial_leisure_settings <- generate_initial_leisure(
    parameters_list = parameters_list,
    leisure_setting_sizes = leisure_setting_sizes
  ) # returns list to initialise RaggedInteger

  # Due to the sampling method used, some leisure settings for which sizes have been drawn are not
  # visited by anyone. Drop those settings and renumber the remaining ones as 1..n, keeping 0 as
  # "no leisure visit":
  visited_leisure_locations <- sort(unique(unlist(initial_leisure_settings)))
  visited_leisure_locations <- visited_leisure_locations[visited_leisure_locations != 0]
  leisure_setting_sizes <- leisure_setting_sizes[visited_leisure_locations]
  initial_leisure_settings <- lapply(initial_leisure_settings, function(visits) {
    visits[visits != 0] <- match(visits[visits != 0], visited_leisure_locations)
    visits
  })

  # The generators assign 1-indexed, contiguous location ids (0 meaning no location), so the number
  # of locations in each setting is the largest id. Households and workplaces always have at least
  # one member, but schools may be empty, as school sizes of 0 can be sampled.
  num_households <- max(initial_households)
  num_schools <- max(initial_school_settings)
  num_workplaces <- max(initial_workplace_settings)
  num_leisure <- max(unlist(initial_leisure_settings))

  if (num_schools <= 2) {
    message(
      "There are less than or equal to 2 schools. Consider the population size may be too small!"
    )
  }
  if (num_workplaces <= 2) {
    message(
      "There are less than or equal to 2 workplaces. Consider the population size may be too small!"
    )
  }

  # Generate the per-location baseline ACH for each setting type, and convert it into a
  # per-location riskiness:
  household_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "household",
    number_of_locations = num_households
  )
  household_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = household_specific_ach,
    parameters_list = parameters_list,
    setting = "household"
  )

  workplace_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "workplace",
    number_of_locations = num_workplaces
  )
  workplace_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = workplace_specific_ach,
    parameters_list = parameters_list,
    setting = "workplace"
  )

  school_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "school",
    number_of_locations = num_schools
  )
  school_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = school_specific_ach,
    parameters_list = parameters_list,
    setting = "school"
  )

  leisure_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "leisure",
    number_of_locations = num_leisure
  )
  leisure_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = leisure_specific_ach,
    parameters_list = parameters_list,
    setting = "leisure"
  )

  setting_sizes <- list(
    household = tabulate(initial_households, num_households),
    school = tabulate(initial_school_settings, num_schools),
    workplace = tabulate(initial_workplace_settings, num_workplaces),

    # This is the number of individuals that *can* visit this location.
    # On any given day, fewer people than this actually will.
    leisure = leisure_setting_sizes
  )

  return(list(
    initial_disease_states = initial_disease_states,
    age_classes = initial_age_classes,
    initial_household_settings = initial_households,
    initial_school_settings = initial_school_settings,
    initial_workplace_settings = initial_workplace_settings,
    initial_leisure_settings = initial_leisure_settings,

    household_specific_ach = household_specific_ach,
    school_specific_ach = school_specific_ach,
    workplace_specific_ach = workplace_specific_ach,
    leisure_specific_ach = leisure_specific_ach,

    household_specific_riskiness = household_specific_riskiness,
    school_specific_riskiness = school_specific_riskiness,
    workplace_specific_riskiness = workplace_specific_riskiness,
    leisure_specific_riskiness = leisure_specific_riskiness,

    setting_sizes = setting_sizes
  ))
}


#' Generate a vector of the initial disease states of all individuals in the population
#'
#' @inheritParams create_variables
#'
#' @family variables
#' @export
generate_initial_disease_states <- function(parameters_list) {
  # Checking that the parameters contain the initial human population size, proportion
  # initially exposed, and a seed:
  if (!("number_initial_S" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_S")
  }
  if (!("number_initial_E" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_E")
  }
  if (!("number_initial_I" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_I")
  }
  if (!("number_initial_R" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_R")
  }
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }

  # Set the seed from the parameter list:
  seed_rng(parameters_list$seed)

  # Create a vector of disease states of length human_population:
  initial_disease_states <- rep("S", parameters_list$human_population)
  population_index <- seq_along(initial_disease_states)

  # Sample indices between 1:human population to set those initially exposed:
  exposed_index <- sample(
    x = population_index,
    size = parameters_list$number_initial_E,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[exposed_index] <- "E"

  # Sample indices between 1:human population (minus those initially exposed) to set those initially infectious:
  infectious_index <- sample(
    x = population_index[-exposed_index],
    size = parameters_list$number_initial_I,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[infectious_index] <- "I_mild"

  # Sample indices between 1:human population (minus those initially exposed) to set those initially infectious:
  recovered_index <- sample(
    x = population_index[-c(exposed_index, infectious_index)],
    size = parameters_list$number_initial_R,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[recovered_index] <- "R"

  # Replace the disease state at the sampled indices with to "E" (Exposed)

  # Return the vector of initial disease states:
  return(initial_disease_states)
}

#' Generate a vector of school assignments for all individuals in the population
#'
#' School sizes are sampled with replacement from a reference dataset. This is
#' known as bootstrapping. The dataset used is [`schools_usa`].
#'
#' @inheritParams create_variables
#' @param initial_age_classes A character vector assigning an age class to each individual
#'
#' @family variables
#' @export
generate_initial_schools <- function(parameters_list, initial_age_classes) {
  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("school_student_staff_ratio" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called school_student_staff_ratio"
    )
  }

  # Calculating number of children and assigning them to schools
  seed_rng(parameters_list$seed)

  schools_usa_total <- dplyr::filter(schools_usa, type == "total")
  empirical_school_sizes <- rep(
    schools_usa_total$size_midpoint,
    schools_usa_total$count
  )

  index_children <- which(initial_age_classes == "child")
  num_children <- length(index_children)

  school_sizes <- c()
  remaining <- num_children

  # Sampling schools and calculating the number of children remaining to allocate
  while (remaining > 0) {
    draw <- sample(empirical_school_sizes, size = 1)
    school_sizes <- c(school_sizes, draw)
    remaining <- remaining - draw
  }

  # Correcting for instances where we overflow above the total number of children
  if (sum(school_sizes) >= num_children) {
    school_sizes[length(school_sizes)] <- school_sizes[length(school_sizes)] -
      (sum(school_sizes) - num_children)
  }

  # Creating schools assignment vector and randomising the ordering
  school_indices <- unlist(sapply(
    seq_along(school_sizes),
    function(i) rep(i, school_sizes[i])
  ))
  child_school_assignments <- sample(school_indices, replace = FALSE)

  # Assign staff to schools
  staff_sizes <- ceiling(
    school_sizes / parameters_list$school_student_staff_ratio
  )
  staff_school_indices <- unlist(sapply(
    seq_along(staff_sizes),
    function(i) rep(i, staff_sizes[i])
  ))
  index_adults <- which(initial_age_classes == "adult")
  index_staff <- sample(index_adults, size = sum(staff_sizes), replace = FALSE)
  staff_school_assignments <- sample(staff_school_indices, replace = FALSE)

  # School assignments for all individuals
  schools_vector <- rep(0L, parameters_list$human_population)
  schools_vector[index_children] <- child_school_assignments
  schools_vector[index_staff] <- staff_school_assignments

  return(schools_vector)
}

#' Gets workplace assignments for all individuals in the population
#'
#' @inheritParams generate_initial_schools
#' @param initial_age_classes A character vector assigning an age class to each individual
#' @param initial_school_settings An integer vector assigning individuals to schools
#'
#' @family variables
#' @export
generate_initial_workplaces <- function(
  parameters_list,
  initial_age_classes,
  initial_school_settings
) {
  # Checking that the parameter list contains the requisite parameters
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("workplace_prop_max" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_prop_max")
  }
  if (!("workplace_a" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_a")
  }
  if (!("workplace_c" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_c")
  }

  # Calculating number of unassigned adults and assigning them to workplaces
  seed_rng(parameters_list$seed)

  index_unassigned_adults <- which(initial_age_classes == "adult" & initial_school_settings == 0)
  workplace_sizes <- sample_offset_truncated_power_distribution(
    N = length(index_unassigned_adults),
    prop_max = parameters_list$workplace_prop_max,
    a = parameters_list$workplace_a,
    c = parameters_list$workplace_c
  )
  workplace_indices <- unlist(sapply(
    seq_along(workplace_sizes),
    function(i) rep(i, workplace_sizes[i])
  ))
  adult_workplace_assignments <- sample(workplace_indices, replace = FALSE)

  # Workplace assignments for all individuals
  workplace_vector <- rep(0L, parameters_list$human_population)
  workplace_vector[index_unassigned_adults] <- adult_workplace_assignments

  return(workplace_vector)
}

#' Generate a list of leisure settings that each individual visits
#'
#' Each element of this list indicates which settings each individual visits on
#' which day. The value 0 indicates that the person stays in on that day.
#'
#' @inheritParams create_variables
#' @param leisure_setting_sizes The sizes of the leisure settings as sampled using `sample_negbinom()`
#'
#' @family variables
#' @export
generate_initial_leisure <- function(parameters_list, leisure_setting_sizes) {
  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("leisure_mean_size" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called leisure_mean_size")
  }
  if (!("leisure_overdispersion_size" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called leisure_overdispersion_size"
    )
  }
  if (!("leisure_mean_number_settings" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called leisure_mean_number_settings"
    )
  }

  # Setting the seed
  seed_rng(parameters_list$seed)

  # Calculating the number of leisure visits that each person makes per week
  leisure_visits_per_person_per_week <- rpois(
    n = parameters_list$human_population,
    lambda = parameters_list$leisure_mean_number_settings
  )
  leisure_visits_per_person_per_week[
    leisure_visits_per_person_per_week > 7
  ] <- 7 # capping it at 1 leisure visit per day (max 7 per week)

  # Populating a list with the leisure visits made by each individual
  leisure_visit_list <- vector(
    mode = "list",
    length = parameters_list$human_population
  )
  for (i in seq_len(parameters_list$human_population)) {
    # Creating a temporary vector of leisure visits for that person
    # -> Each element indicates where they visit on which day of the week
    #    and a 0 means nowhere visited on that day of the week
    temp_leisure_visit <- rep(0L, 7)

    # Sampling which locations individuals visit for their leisure visits (weighted according to leisure setting size)
    temp_location_leisure_visits <- sample.int(
      n = length(leisure_setting_sizes),
      size = leisure_visits_per_person_per_week[i],
      replace = FALSE,
      prob = leisure_setting_sizes
    )

    # Sampling which day(s) of the week the individual makes those visit(s) and assigning visits randomly
    days_visits_made <- sample(
      x = 1:7,
      size = leisure_visits_per_person_per_week[i],
      replace = FALSE
    )
    if (leisure_visits_per_person_per_week[i] == 1) {
      temp_leisure_visit[days_visits_made] <- temp_location_leisure_visits
    } else {
      temp_leisure_visit[days_visits_made] <- sample(
        x = temp_location_leisure_visits,
        size = leisure_visits_per_person_per_week[i],
        replace = FALSE
      )
    }
    leisure_visit_list[[i]] <- temp_leisure_visit
  }

  return(leisure_visit_list) # a list where each element contains a vector that specifies the ids of the leisure settings
  # that each individual visits e.g. list(c(2, 6, 19, 35), c(1, 8), c(6, 10, 45)... etc)
}

#' Generates a vector of households for all individuals in the population
#'
#' Households are sampled with replacement from a reference dataset. This is
#' known as bootstrapping. The dataset used is
#' [`baseline_household_demographics_usa`]. This function generates both the
#' household and age class assignments together.
#'
#' @inheritParams create_variables
#'
#' @family variables
#' @export
generate_initial_households <- function(parameters_list) {
  ## Using data from RTI's synthetic population for San Francisco to bootstrap https://fred.publichealth.pitt.edu/syn_pops
  ref_panel <- as.matrix(baseline_household_demographics_usa)
  panel_household_sizes <- rowSums(ref_panel)

  ## Sampling random households from the reference panel until there is a place for everyone.
  ## Every household has at least one member, so at most human_population households are needed.
  sampled_households <- integer(parameters_list$human_population)
  num_households <- 0L
  num_individuals <- 0
  while (num_individuals < parameters_list$human_population) {
    num_households <- num_households + 1L
    sampled_households[num_households] <- sample(seq_len(nrow(ref_panel)), 1)
    num_individuals <- num_individuals + panel_household_sizes[sampled_households[num_households]]
  }
  sampled_households <- sampled_households[seq_len(num_households)]

  ## Expanding out the households into individuals, listing the children, adults and elderly
  ## members of each household in turn
  household_members <- t(ref_panel[sampled_households, , drop = FALSE])
  age_class_vector <- rep(
    x = rep(colnames(ref_panel), num_households),
    times = household_members
  )
  individual_households <- rep(
    x = seq_len(num_households),
    times = panel_household_sizes[sampled_households]
  )

  ## The last household sampled may not fit in the population, so drop its members that don't
  age_class_vector <- age_class_vector[seq_len(parameters_list$human_population)]
  individual_households <- individual_households[seq_len(parameters_list$human_population)]

  ## Scrambling the order of individuals so that household members don't appear right next to each other
  ## -> This might not be needed, need to give this some thought
  scrambled_index <- sample(
    x = 1:parameters_list$human_population,
    size = parameters_list$human_population,
    replace = FALSE
  )

  return(list(
    individual_households = individual_households[scrambled_index],
    age_class_vector = age_class_vector[scrambled_index]
  ))
}
