DISEASE_STATES <- c("S", "E", "I_mild", "I_hosp", "R", "D")
AGE_CLASSES <- c("child", "adult", "elderly")

#' Generate a list of the model variables
#'
#' @param parameters_list A list of model parameters as generated by `get_parameters`
#' @param population_data The population data, as generated by [generate_population_data()]
#'
#' @family variables
#' @export
create_variables <- function(parameters_list, population_data) {
  disease_state_variable <- individual::CategoricalVariable$new(
    categories = DISEASE_STATES,
    initial_values = population_data$initial_disease_states
  )

  age_class_variable <- individual::CategoricalVariable$new(
    categories = AGE_CLASSES,
    initial_values = population_data$age_classes
  )

  # Everyone belongs to a household, so household ids start at 1. For schools,
  # workplaces and leisure, 0 means the individual doesn't attend any location.
  # Ids are formatted with "%d" so that large ids aren't written in scientific
  # notation (eg. `as.character(1e5)` is "1e+05").
  household_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", seq_along(population_data$setting_sizes$household)),
    initial_values = sprintf("%d", population_data$initial_household_settings)
  )

  school_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$school)),
    initial_values = sprintf("%d", population_data$initial_school_settings)
  )

  workplace_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$workplace)),
    initial_values = sprintf("%d", population_data$initial_workplace_settings)
  )

  leisure_variable <- individual::RaggedInteger$new(
    initial_values = population_data$initial_leisure_settings
  )

  ## Creating initial CategoricalVariable tracking leisure location an individiual goes to on a given day, which we will dynamically update
  specific_leisure_variable <- individual::CategoricalVariable$new(
    categories = sprintf("%d", 0:length(population_data$setting_sizes$leisure)),
    initial_values = rep("0", parameters_list$human_population)
  )

  return(list(
    disease_state = disease_state_variable,
    age_class = age_class_variable,
    household = household_variable,
    school = school_variable,
    workplace = workplace_variable,
    leisure = leisure_variable,
    specific_leisure = specific_leisure_variable
  ))
}

#' Generate a population for the given parameters
#'
#' This will sample individuals' initial state and assign them to households and
#' other locations. It also draws the baseline ACH and riskiness of each
#' location. Interventions are not part of the population: see
#' [generate_intervention_data()].
#'
#' Households and schools and workplaces depend on the
#' `school_workplace_sampling` parameter:
#'
#' * `"reference"`: households are sampled with replacement from
#'   `synthetic_population` when given, and from the bundled San Francisco
#'   households ([`baseline_household_demographics_usa`]) otherwise. School
#'   sizes are sampled from [`schools_usa`] and workplace sizes from a power-law
#'   distribution. Every child goes to school and every other adult to work.
#' * `"rti"`: the population is the whole of `synthetic_population`, with each
#'   person simulated once in their own household, school and workplace. School
#'   staff are drawn from working adults. This needs a `synthetic_population`
#'   with `school_id` and `workplace_id` columns, and `human_population` must be
#'   its number of people: see [set_synthetic_population_size()]. The
#'   population can't be scaled down, because settings would be left with too
#'   few members. See [generate_rti_schools_and_workplaces()].
#'
#' @param parameters_list A list of model parameters as generated by `get_parameters`
#' @param synthetic_population Optional `helios_synthetic_population`, as
#'   returned by [rti_population()] or [read_synthetic_population()]. It isn't a
#'   parameter because it's large, and parameter lists are saved and reused. To
#'   simulate it, generate the population first and pass it to
#'   [run_simulation()] as `population_data`.
#' @family variables
#' @export
generate_population_data <- function(parameters_list, synthetic_population = NULL) {
  rti_sampling <- identical(parameters_list$school_workplace_sampling, "rti")
  if (!is.null(synthetic_population)) {
    validate_synthetic_population(synthetic_population)
  }
  if (rti_sampling) {
    if (is.null(synthetic_population)) {
      stop(
        "school_workplace_sampling = \"rti\" needs a synthetic population, eg. ",
        "`generate_population_data(parameters_list, synthetic_population = rti_population(\"06075\"))`"
      )
    }
    check_synthetic_population_settings(synthetic_population)
    if (parameters_list$human_population != nrow(synthetic_population$people)) {
      stop(
        "school_workplace_sampling = \"rti\" simulates the whole synthetic population, so human_population must be ",
        nrow(synthetic_population$people), ", not ", parameters_list$human_population,
        ". Use `set_synthetic_population_size(parameters_list, synthetic_population)`"
      )
    }
  }

  # Disease state variable
  initial_disease_states <- generate_initial_disease_states(parameters_list = parameters_list)

  if (rti_sampling) {
    # Everyone in the synthetic population, in their own household
    initial_households <- synthetic_population$people$household_id
    initial_age_classes <- age_class_from_age(synthetic_population$people$age)
    settings <- generate_rti_schools_and_workplaces(
      parameters_list = parameters_list,
      synthetic_population = synthetic_population,
      initial_age_classes = initial_age_classes
    )
    initial_school_settings <- settings$school_settings
    initial_workplace_settings <- settings$workplace_settings
  } else {
    # Bootstrap sampling of households, and the ages of their members, from the synthetic population
    # (by default, RTI's synthetic population for San Francisco)
    household_age_list <- generate_initial_households(
      parameters_list = parameters_list,
      synthetic_population = synthetic_population
    )
    initial_age_classes <- household_age_list$age_class_vector
    initial_households <- household_age_list$individual_households

    initial_school_settings <- generate_initial_schools(
      parameters_list = parameters_list,
      initial_age_classes = initial_age_classes
    )

    initial_workplace_settings <- generate_initial_workplaces(
      parameters_list = parameters_list,
      initial_age_classes = initial_age_classes,
      initial_school_settings = initial_school_settings
    )
  }

  # Generating the number and sizes of each leisure setting
  leisure_setting_sizes <- sample_negbinom(
    N = parameters_list$human_population,
    prop_max = parameters_list$leisure_prop_max,
    mu = parameters_list$leisure_mean_size,
    size = parameters_list$leisure_overdispersion_size
  )

  # Initialise and populate the leisure setting variable that stores all the leisure locations an individual COULD go to
  initial_leisure_settings <- generate_initial_leisure(
    parameters_list = parameters_list,
    leisure_setting_sizes = leisure_setting_sizes
  ) # returns list to initialise RaggedInteger

  # Due to the sampling method used, some leisure settings for which sizes have been drawn are not
  # visited by anyone. Drop those settings and renumber the remaining ones as 1..n, keeping 0 as
  # "no leisure visit":
  visited_leisure_locations <- sort(unique(unlist(initial_leisure_settings)))
  visited_leisure_locations <- visited_leisure_locations[visited_leisure_locations != 0]
  leisure_setting_sizes <- leisure_setting_sizes[visited_leisure_locations]
  # new_leisure_location[old id + 1] is the new id
  new_leisure_location <- c(0L, match(seq_len(max(visited_leisure_locations, 0L)), visited_leisure_locations, nomatch = 0L))
  initial_leisure_settings <- lapply(initial_leisure_settings, function(visits) new_leisure_location[visits + 1L])

  # The generators assign 1-indexed, contiguous location ids (0 meaning no location), so the number
  # of locations in each setting is the largest id. Households and workplaces always have at least
  # one member, but schools may be empty in "reference" mode, as school sizes of 0 can be sampled.
  num_households <- max(initial_households)
  num_schools <- max(initial_school_settings)
  num_workplaces <- max(initial_workplace_settings)
  num_leisure <- max(unlist(initial_leisure_settings))

  if (num_schools <= 2) {
    message(
      "There are less than or equal to 2 schools. Consider the population size may be too small!"
    )
  }
  if (num_workplaces <= 2) {
    message(
      "There are less than or equal to 2 workplaces. Consider the population size may be too small!"
    )
  }

  # Generate the per-location baseline ACH for each setting type, and convert it into a
  # per-location riskiness:
  household_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "household",
    number_of_locations = num_households
  )
  household_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = household_specific_ach,
    parameters_list = parameters_list,
    setting = "household"
  )

  workplace_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "workplace",
    number_of_locations = num_workplaces
  )
  workplace_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = workplace_specific_ach,
    parameters_list = parameters_list,
    setting = "workplace"
  )

  school_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "school",
    number_of_locations = num_schools
  )
  school_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = school_specific_ach,
    parameters_list = parameters_list,
    setting = "school"
  )

  leisure_specific_ach <- generate_setting_specific_ach(
    parameters_list = parameters_list,
    setting = "leisure",
    number_of_locations = num_leisure
  )
  leisure_specific_riskiness <- convert_ach_to_riskiness(
    ach_values = leisure_specific_ach,
    parameters_list = parameters_list,
    setting = "leisure"
  )

  setting_sizes <- list(
    household = tabulate(initial_households, num_households),
    school = tabulate(initial_school_settings, num_schools),
    workplace = tabulate(initial_workplace_settings, num_workplaces),

    # This is the number of individuals that *can* visit this location.
    # On any given day, fewer people than this actually will.
    leisure = leisure_setting_sizes
  )

  return(list(
    initial_disease_states = initial_disease_states,
    age_classes = initial_age_classes,
    initial_household_settings = initial_households,
    initial_school_settings = initial_school_settings,
    initial_workplace_settings = initial_workplace_settings,
    initial_leisure_settings = initial_leisure_settings,

    household_specific_ach = household_specific_ach,
    school_specific_ach = school_specific_ach,
    workplace_specific_ach = workplace_specific_ach,
    leisure_specific_ach = leisure_specific_ach,

    household_specific_riskiness = household_specific_riskiness,
    school_specific_riskiness = school_specific_riskiness,
    workplace_specific_riskiness = workplace_specific_riskiness,
    leisure_specific_riskiness = leisure_specific_riskiness,

    setting_sizes = setting_sizes
  ))
}


#' Generate a vector of the initial disease states of all individuals in the population
#'
#' @inheritParams create_variables
#'
#' @family variables
#' @export
generate_initial_disease_states <- function(parameters_list) {
  # Checking that the parameters contain the initial human population size, proportion
  # initially exposed, and a seed:
  if (!("number_initial_S" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_S")
  }
  if (!("number_initial_E" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_E")
  }
  if (!("number_initial_I" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_I")
  }
  if (!("number_initial_R" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called number_initial_R")
  }
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }

  # Set the seed from the parameter list:
  seed_rng(parameters_list$seed)

  # Create a vector of disease states of length human_population:
  initial_disease_states <- rep("S", parameters_list$human_population)
  population_index <- seq_along(initial_disease_states)

  # Sample indices between 1:human population to set those initially exposed:
  exposed_index <- sample(
    x = population_index,
    size = parameters_list$number_initial_E,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[exposed_index] <- "E"

  # Sample indices between 1:human population (minus those initially exposed) to set those initially infectious:
  infectious_index <- sample(
    x = population_index[-exposed_index],
    size = parameters_list$number_initial_I,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[infectious_index] <- "I_mild"

  # Sample indices between 1:human population (minus those initially exposed) to set those initially infectious:
  recovered_index <- sample(
    x = population_index[-c(exposed_index, infectious_index)],
    size = parameters_list$number_initial_R,
    replace = FALSE,
    prob = NULL
  )
  initial_disease_states[recovered_index] <- "R"

  # Replace the disease state at the sampled indices with to "E" (Exposed)

  # Return the vector of initial disease states:
  return(initial_disease_states)
}

#' Generate a vector of school assignments for all individuals in the population
#'
#' School sizes are sampled with replacement from a reference dataset. This is
#' known as bootstrapping. The dataset used is [`schools_usa`].
#'
#' @inheritParams create_variables
#' @param initial_age_classes A character vector assigning an age class to each individual
#'
#' @family variables
#' @export
generate_initial_schools <- function(parameters_list, initial_age_classes) {
  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("school_student_staff_ratio" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called school_student_staff_ratio"
    )
  }

  # Calculating number of children and assigning them to schools
  seed_rng(parameters_list$seed)

  schools_usa_total <- dplyr::filter(schools_usa, type == "total")
  empirical_school_sizes <- rep(
    schools_usa_total$size_midpoint,
    schools_usa_total$count
  )

  index_children <- which(initial_age_classes == "child")
  num_children <- length(index_children)

  school_sizes <- c()
  remaining <- num_children

  # Sampling schools and calculating the number of children remaining to allocate
  while (remaining > 0) {
    draw <- sample(empirical_school_sizes, size = 1)
    school_sizes <- c(school_sizes, draw)
    remaining <- remaining - draw
  }

  # Correcting for instances where we overflow above the total number of children
  if (sum(school_sizes) >= num_children) {
    school_sizes[length(school_sizes)] <- school_sizes[length(school_sizes)] -
      (sum(school_sizes) - num_children)
  }

  # Creating schools assignment vector and randomising the ordering
  school_indices <- unlist(sapply(
    seq_along(school_sizes),
    function(i) rep(i, school_sizes[i])
  ))
  child_school_assignments <- sample(school_indices, replace = FALSE)

  # Assign staff to schools
  staff_sizes <- ceiling(
    school_sizes / parameters_list$school_student_staff_ratio
  )
  staff_school_indices <- unlist(sapply(
    seq_along(staff_sizes),
    function(i) rep(i, staff_sizes[i])
  ))
  index_adults <- which(initial_age_classes == "adult")
  index_staff <- sample(index_adults, size = sum(staff_sizes), replace = FALSE)
  staff_school_assignments <- sample(staff_school_indices, replace = FALSE)

  # School assignments for all individuals
  schools_vector <- rep(0L, parameters_list$human_population)
  schools_vector[index_children] <- child_school_assignments
  schools_vector[index_staff] <- staff_school_assignments

  return(schools_vector)
}

#' Gets workplace assignments for all individuals in the population
#'
#' @inheritParams generate_initial_schools
#' @param initial_age_classes A character vector assigning an age class to each individual
#' @param initial_school_settings An integer vector assigning individuals to schools
#'
#' @family variables
#' @export
generate_initial_workplaces <- function(
  parameters_list,
  initial_age_classes,
  initial_school_settings
) {
  # Checking that the parameter list contains the requisite parameters
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("workplace_prop_max" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_prop_max")
  }
  if (!("workplace_a" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_a")
  }
  if (!("workplace_c" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called workplace_c")
  }

  # Calculating number of unassigned adults and assigning them to workplaces
  seed_rng(parameters_list$seed)

  index_unassigned_adults <- which(initial_age_classes == "adult" & initial_school_settings == 0)
  workplace_sizes <- sample_offset_truncated_power_distribution(
    N = length(index_unassigned_adults),
    prop_max = parameters_list$workplace_prop_max,
    a = parameters_list$workplace_a,
    c = parameters_list$workplace_c
  )
  workplace_indices <- unlist(sapply(
    seq_along(workplace_sizes),
    function(i) rep(i, workplace_sizes[i])
  ))
  adult_workplace_assignments <- sample(workplace_indices, replace = FALSE)

  # Workplace assignments for all individuals
  workplace_vector <- rep(0L, parameters_list$human_population)
  workplace_vector[index_unassigned_adults] <- adult_workplace_assignments

  return(workplace_vector)
}

#' Generate a list of leisure settings that each individual visits
#'
#' Each element of this list indicates which settings each individual visits on
#' which day. The value 0 indicates that the person stays in on that day.
#'
#' @inheritParams create_variables
#' @param leisure_setting_sizes The sizes of the leisure settings as sampled using `sample_negbinom()`
#'
#' @family variables
#' @export
generate_initial_leisure <- function(parameters_list, leisure_setting_sizes) {
  # Check that the requisite parameters are present:
  if (!("human_population" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called human_population")
  }
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("leisure_mean_size" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called leisure_mean_size")
  }
  if (!("leisure_overdispersion_size" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called leisure_overdispersion_size"
    )
  }
  if (!("leisure_mean_number_settings" %in% names(parameters_list))) {
    stop(
      "parameters list must contain a variable called leisure_mean_number_settings"
    )
  }

  # Setting the seed
  seed_rng(parameters_list$seed)

  # Calculating the number of leisure visits that each person makes per week
  leisure_visits_per_person_per_week <- rpois(
    n = parameters_list$human_population,
    lambda = parameters_list$leisure_mean_number_settings
  )
  leisure_visits_per_person_per_week[
    leisure_visits_per_person_per_week > 7
  ] <- 7 # capping it at 1 leisure visit per day (max 7 per week)

  # Sampling which locations individuals visit (weighted according to leisure setting size), without
  # replacement for each individual. Visit j of every individual is drawn at once, with replacement,
  # and draws that repeat one of that individual's earlier visits are redrawn: this gives the same
  # distribution as sampling without replacement, without a pass over every setting per individual.
  visits <- leisure_visits_per_person_per_week
  if (max(0L, visits) > sum(leisure_setting_sizes > 0)) {
    stop("too few leisure settings for the number of leisure visits")
  }
  locations <- matrix(0L, parameters_list$human_population, 7)
  for (j in seq_len(max(0L, visits))) {
    pending <- which(visits >= j)
    while (length(pending)) {
      locations[pending, j] <- sample.int(
        n = length(leisure_setting_sizes),
        size = length(pending),
        replace = TRUE,
        prob = leisure_setting_sizes
      )
      repeated <- rowSums(locations[pending, seq_len(j - 1), drop = FALSE] == locations[pending, j]) > 0
      pending <- pending[repeated]
    }
  }

  # Sampling which day(s) of the week the individual makes those visit(s): visit j is made on the
  # j-th day of a random ordering of the week, and a 0 means nowhere visited on that day
  n <- parameters_list$human_population
  individual <- rep(seq_len(n), 7)
  by_individual <- order(individual, stats::runif(n * 7))
  day_order <- matrix((by_individual - 1L) %/% n + 1L, n, 7, byrow = TRUE)
  leisure_week <- matrix(0L, n, 7)
  leisure_week[cbind(individual, as.vector(day_order))] <- locations

  leisure_visit_list <- unname(split(as.vector(t(leisure_week)), rep(seq_len(n), each = 7)))

  return(leisure_visit_list) # a list where each element contains a vector that specifies the ids of the leisure settings
  # that each individual visits e.g. list(c(2, 6, 19, 35), c(1, 8), c(6, 10, 45)... etc)
}

#' Generates a vector of households for all individuals in the population
#'
#' Households are sampled with replacement from a reference dataset. This is
#' known as bootstrapping. The dataset used is `synthetic_population` when given,
#' and [`baseline_household_demographics_usa`] otherwise. This function generates
#' both the household and age class assignments together.
#'
#' Ages in a synthetic population are grouped into the same age classes as
#' [`baseline_household_demographics_usa`]: children are aged 18 or under, adults
#' 19 to 69, and the elderly 70 or over.
#'
#' @inheritParams create_variables
#' @param synthetic_population Optional `helios_synthetic_population`, as
#'   returned by [rti_population()] or [read_synthetic_population()], to sample
#'   households from.
#'
#' @return A list with `individual_households` and `age_class_vector`, giving
#'   each individual's household and age class.
#'
#' @family variables
#' @export
generate_initial_households <- function(parameters_list, synthetic_population = NULL) {
  ## Each reference household is a run of rows in a table of people, which lists the members of
  ## each household in turn
  if (is.null(synthetic_population)) {
    ## Using data from RTI's synthetic population for San Francisco to bootstrap
    ## https://github.com/RTIInternational/SyntheticPopulations
    ref_panel <- as.matrix(baseline_household_demographics_usa)
    panel_household_sizes <- rowSums(ref_panel)
    age_classes <- rep(
      x = rep(colnames(ref_panel), nrow(ref_panel)),
      times = t(ref_panel)
    )
  } else {
    household_ids <- synthetic_population$people$household_id
    panel_household_sizes <- tabulate(household_ids, max(0L, household_ids))
    person_rows <- order(household_ids)
    age_classes <- age_class_from_age(synthetic_population$people$age[person_rows])
  }

  ## Every household must have a member, so that each sampled household adds at least one individual
  ## and the loop below ends
  if (length(panel_household_sizes) == 0) {
    stop("there are no households to sample from")
  }
  if (any(panel_household_sizes == 0)) {
    stop("every household to sample from must have at least one member")
  }
  first_rows <- cumsum(panel_household_sizes) - panel_household_sizes + 1

  ## Sampling random households from the reference panel until there is a place for everyone.
  ## Every household has at least one member, so at most human_population households are needed.
  sampled_households <- integer(parameters_list$human_population)
  num_households <- 0L
  num_individuals <- 0
  while (num_individuals < parameters_list$human_population) {
    num_households <- num_households + 1L
    sampled_households[num_households] <- sample.int(length(panel_household_sizes), 1)
    num_individuals <- num_individuals + panel_household_sizes[sampled_households[num_households]]
  }
  sampled_households <- sampled_households[seq_len(num_households)]

  ## Expanding out the households into individuals
  rows <- sequence(panel_household_sizes[sampled_households], from = first_rows[sampled_households])
  individual_households <- rep(
    x = seq_len(num_households),
    times = panel_household_sizes[sampled_households]
  )

  ## The last household sampled may not fit in the population, so drop its members that don't
  rows <- rows[seq_len(parameters_list$human_population)]
  individual_households <- individual_households[seq_len(parameters_list$human_population)]

  ## Scrambling the order of individuals so that household members don't appear right next to each other
  ## -> This might not be needed, need to give this some thought
  scrambled_index <- sample(
    x = 1:parameters_list$human_population,
    size = parameters_list$human_population,
    replace = FALSE
  )
  rows <- rows[scrambled_index]

  list(
    individual_households = individual_households[scrambled_index],
    age_class_vector = age_classes[rows]
  )
}

# Age classes used by baseline_household_demographics_usa (see data-raw/DATASET.R)
age_class_from_age <- function(age) {
  AGE_CLASSES[findInterval(age, c(19, 70)) + 1]
}

#' Assign individuals to schools and workplaces from a synthetic population
#'
#' Used by [generate_population_data()] when `school_workplace_sampling` is
#' `"rti"`. There is one individual for each person in the synthetic
#' population, in the same order, who keeps their school and workplace.
#'
#' The synthetic population has no school staff, so each school gets
#' `ceiling(students / school_student_staff_ratio)` staff, as in
#' [generate_initial_schools()]. Staff are drawn at random from adults who have a
#' workplace and no school, and leave their workplace. Workplaces left with no
#' one are dropped.
#'
#' School and workplace ids are renumbered `1, 2, ...`, with 0 meaning none.
#'
#' @inheritParams generate_initial_households
#' @param synthetic_population A `helios_synthetic_population` whose `people`
#'   have `school_id` and `workplace_id` columns.
#' @param initial_age_classes A character vector assigning an age class to each
#'   person in `synthetic_population$people`
#'
#' @return A list with integer vectors `school_settings` and
#'   `workplace_settings`, giving each individual's school and workplace.
#'
#' @family variables
#' @export
generate_rti_schools_and_workplaces <- function(
  parameters_list,
  synthetic_population,
  initial_age_classes
) {
  if (!("seed" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called seed")
  }
  if (!("school_student_staff_ratio" %in% names(parameters_list))) {
    stop("parameters list must contain a variable called school_student_staff_ratio")
  }
  check_synthetic_population_settings(synthetic_population)

  seed_rng(parameters_list$seed)

  schools <- renumber_settings(synthetic_population$people$school_id)
  workplaces <- renumber_settings(synthetic_population$people$workplace_id)

  # Staff are drawn from working adults, so that no employment is invented
  staff_sizes <- ceiling(tabulate(schools, max(schools)) / parameters_list$school_student_staff_ratio)
  index_candidates <- which(initial_age_classes == "adult" & workplaces != 0 & schools == 0)
  if (sum(staff_sizes) > length(index_candidates)) {
    stop(
      "schools need ", sum(staff_sizes), " staff, but only ", length(index_candidates),
      " adults have a workplace and no school"
    )
  }
  index_staff <- index_candidates[sample.int(length(index_candidates), sum(staff_sizes))]
  staff_school_indices <- rep(seq_along(staff_sizes), staff_sizes)
  schools[index_staff] <- staff_school_indices[sample.int(length(staff_school_indices))]
  workplaces[index_staff] <- 0L

  list(
    school_settings = schools,
    workplace_settings = renumber_settings(workplaces)
  )
}

# Renumbers the setting ids present to 1..n in order of id, with NA and 0 becoming 0
renumber_settings <- function(ids) {
  ids[is.na(ids)] <- 0L
  present <- sort(unique(ids[ids != 0]))
  match(ids, present, nomatch = 0L)
}

# Errors if a synthetic population can't be used to sample schools and workplaces
check_synthetic_population_settings <- function(synthetic_population) {
  for (column in c("school_id", "workplace_id")) {
    if (!column %in% names(synthetic_population$people)) {
      stop(
        "school_workplace_sampling = \"rti\" needs a ", column, " column in the synthetic population's `people`"
      )
    }
  }
}
